const path = require("path");

/**
 * Generates a final path based on the provided command line argument and a base path.
 *
 * @param {string[]} args - Command line arguments.
 * @param {string} [basePath=process.cwd()] - The base path to start from. Defaults to the current working directory.
 * @returns {string} - The final path generated by either using the provided argument or the base path.
 */
function generatePath(args, basePath = process.cwd()) {
  let finalPath = basePath;

  // Check if command line arguments exist and at least one argument (other than 'node' and the script file) is provided.
  if (process.argv && process.argv.length > 2) {
    // Extract the third command line argument, as the first two are reserved for 'node' and the script file.
    const arg = process.argv[2];

    // Ensure the argument is not empty and does not start with a forward slash ("/").
    // If the argument is valid, concatenate it with the base path using the 'path.join' method.
    // This helps in constructing the final path for the file or directory to be accessed.
    if (arg && arg[0] !== "/") {
      finalPath = path.join(basePath, arg);
    }
  }

  return finalPath;
}

module.exports = generatePath;
